version: '3.8'

services:
  punto_venta:
    build: ventas_2024
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://ventas_2024:3306/ventas2024?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: deikyt2002.
    restart: always
    networks:
      - mynetwork
    # Aquí ya no es necesario el entrypoint con wait-for-it.sh

  ventas_2024:
    image: mysql:8.0.33
    container_name: ventas_2024
    environment:
      MYSQL_ROOT_PASSWORD: deikyt2002.
      MYSQL_PASSWORD: deikyt2002.
      MYSQL_DATABASE: ventas2024
    ports:
      - "3307:3306"
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
